# Frontend build configuration
steps:
  # ビルド
  - name: 'node:20'
    entrypoint: yarn
    args: ['install']

  - name: 'node:20'
    entrypoint: yarn
    args: ['build']

  # Dockerイメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/survey-repo/survey-frontend:$COMMIT_SHA',
      '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/survey-repo/survey-frontend:latest',
      '.'
    ]

  # イメージのプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/survey-repo/survey-frontend:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/survey-repo/survey-frontend:latest']

  # Cloud Runへのデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'survey-frontend-${_ENV}'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/survey-repo/survey-frontend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

substitutions:
  _ENV: dev
  _REGION: asia-northeast1

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/survey-repo/survey-frontend:$COMMIT_SHA'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/survey-repo/survey-frontend:latest'
