steps:
  # Dockerイメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/survey-repo/survey-backend:$COMMIT_SHA',
      '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/survey-repo/survey-backend:latest',
      '.'
    ]

  # イメージのプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/survey-repo/survey-backend:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/survey-repo/survey-backend:latest']

  # Cloud Runへのデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'survey-backend-${_ENV}'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/survey-repo/survey-backend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--vpc-connector'
      - 'survey-vpc-connector-${_ENV}'
      - '--allow-unauthenticated'

substitutions:
  _ENV: dev
  _REGION: asia-northeast1

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/survey-repo/survey-backend:$COMMIT_SHA'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/survey-repo/survey-backend:latest'
